### PR TITLE
한글화 작업

### PR DESCRIPTION
**Pull request by junghak-lee**
*Issue #50, if available:*

*Description of changes:*
done Korean translation for section "Working With Albums"

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by gabehollombe-aws** [comment]
Thank you SO much for your translation work here!  This branch has a few conflicting edits at this point (likely due to my recent updates of some of the english content).  If you can update this branch a bit more so we don't have conflicts, I'm excited to get this merged and deployed. <3

**Comment by gabehollombe-aws** [comment]
Question:  It looks like merging this will overwrite the English language content for this workshop.  Instead, do you think it makes more sense if we just cross-link to the english and korean language versions? Or was your intent with this PR to add a language switching mode to the content?

I can link to https://awskrug.github.io/amplify-photo-gallery-workshop/ from http://amplify-workshop.go-aws.com/  and you can like to http://amplify-workshop.go-aws.com/  from https://awskrug.github.io/amplify-photo-gallery-workshop/ 

Does that make sense?

**Comment by Lana-Banana** [comment]
> It looks like merging this will overwrite the English language content for this workshop. Instead, do you think it makes more sense if we just cross-link to the english and korean language versions? Or was your intent with this PR to add a language switching mode to the content?

Ooops; This PR seems to be a mistake.
Translation work is for studying in the AWS Korean user group.
I think this PR should be closed without merging. :)
Thank you for the good material.

**Comment by gabehollombe-aws** [comment]
Closing without merge as per the comment above by @Lana-Banana

**Pull request closed without merging**
